export const skillsContent = [
    {
        imagemPrincipal: "./img/JS.png",
        arquivoBTN: "js-btn",
        arquivoSVG: "js-svg",
        divModal: "js-modal",
        tituloDiv: "titulo-js",
        listaCursos: "js-lista",
    },
    {
        imagemPrincipal: "./img/ts.png",
        arquivoBTN: "ts-btn",
        arquivoSVG: "ts-svg",
        divModal: "ts-modal",
        tituloDiv: "titulo-ts",
        listaCursos: "ts-lista",
    },
    {
        imagemPrincipal: "./img/react.png",
        arquivoBTN: "rc-btn",
        arquivoSVG: "rc-svg",
        divModal: "rc-modal",
        tituloDiv: "titulo-rc",
        listaCursos: "rc-lista",
    },
    {
        imagemPrincipal: "./img/CSS.png",
        arquivoBTN: "css-btn",
        arquivoSVG: "css-svg",
        divModal: "css-modal",
        tituloDiv: "titulo-css",
        listaCursos: "css-lista",
    },
    {
        imagemPrincipal: "./img/node.png",
        arquivoBTN: "node-btn",
        arquivoSVG: "node-svg",
        divModal: "node-modal",
        tituloDiv: "titulo-node",
        listaCursos: "node-lista",
    },
    {
        imagemPrincipal: "./img/git.png",
        arquivoBTN: "git-btn",
        arquivoSVG: "git-svg",
        divModal: "git-modal",
        tituloDiv: "titulo-git",
        listaCursos: "git-lista",
    },
    {
        imagemPrincipal: "./img/figma.png",
        arquivoBTN: "desing-btn",
        arquivoSVG: "desing-svg",
        divModal: "desing-modal",
        tituloDiv: "titulo-desing",
        listaCursos: "desing-lista",
    },
    {
        imagemPrincipal: "./img/books.png",
        arquivoBTN: "books-btn",
        arquivoSVG: "books-svg",
        divModal: "books-modal",
        tituloDiv: "titulo-books",
        listaCursos: "books-lista",
    },
    {
        imagemPrincipal: "./img/agile.png",
        arquivoBTN: "scrum-btn",
        arquivoSVG: "scrum-svg",
        divModal: "scrum-modal",
        tituloDiv: "titulo-scrum",
        listaCursos: "scrum-lista",
    },
]